server:
  port: ${server_port:8081}

spring:
  application:
    name: caller-service

security:
  API_TOKEN: ${API_TOKEN}

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/